E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("ki,akbj->bjai", extract_mat(F, "oo", o, v), extract_mat(c2, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("kj,aibk->bjai", extract_mat(F, "oo", o, v), extract_mat(c2, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("ac,cibj->bjai", extract_mat(F, "vv", o, v), extract_mat(c2, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("bc,cjai->bjai", extract_mat(F, "vv", o, v), extract_mat(c2, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("cibj,ac->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g_p, "IIvv", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("cjai,bc->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g_p, "IIvv", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("akbj,ki->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g_p, "IIoo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("aibk,kj->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g_p, "IIoo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("kcai,ckbj->bjai", extract_mat(L, "ovvo", o, v), extract_mat(c2, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("kcbj,ckai->bjai", extract_mat(L, "ovvo", o, v), extract_mat(c2, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("cidj,acbd->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "vvvv", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("ciak,kcbj->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("cibk,kjac->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "oovv", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("cjak,kibc->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "oovv", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("cjbk,kcai->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("akbl,kilj->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "oooo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -4.00000000  * fixed_einsum("ckai,Akc,Abj->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g_p, "IVov", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -4.00000000  * fixed_einsum("ckbj,Akc,Aai->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g_p, "IVov", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("ciak,Akc,Abj->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g_p, "IVov", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("cibj,Akc,Aak->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g_p, "IVov", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("cjai,Akc,Abk->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g_p, "IVov", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("cjbk,Akc,Aai->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g_p, "IVov", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("akbj,Akc,Aci->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g_p, "IVov", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("aibk,Akc,Acj->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g_p, "IVov", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("kcld,ckdi,albj->bjai", extract_mat(L, "ovov", o, v), extract_mat(c2, "vovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("kcld,ckdj,aibl->bjai", extract_mat(L, "ovov", o, v), extract_mat(c2, "vovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("kcld,ckal,dibj->bjai", extract_mat(L, "ovov", o, v), extract_mat(c2, "vovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("kcld,ckbl,djai->bjai", extract_mat(L, "ovov", o, v), extract_mat(c2, "vovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("kcld,ckai,dlbj->bjai", extract_mat(L, "ovov", o, v), extract_mat(c2, "vovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("kcld,ckbj,dlai->bjai", extract_mat(L, "ovov", o, v), extract_mat(c2, "vovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("cidj,kcld,akbl->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("ciak,kdlc,dlbj->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("cibk,kdlc,djal->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("cjak,kdlc,dibl->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("cjbk,kdlc,dlai->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("akbl,kcld,cidj->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("ciak,kcld,dlbj->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("cibj,kcld,dlak->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("cjai,kcld,dlbk->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("cjbk,kcld,dlai->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("akbj,kcld,cidl->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("aibk,kcld,cjdl->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
