name = "SpinAdaptedSecondQuantization"
uuid = "07861ef0-4e5e-45a9-88ac-f5a78d3027be"
authors = ["MarcusTL12 <marcuspaafjellet@gmail.com>", "torhaugl <tor.s.haugland@ntnu.no>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Permutations = "2ae35dd2-176d-5d53-8349-f30d82d94d4f"

[compat]
DataStructures = "0.18"
Permutations = "0.4"
