E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("ki,akbj->bjai", extract_mat(F, "oo", o, v), extract_mat(c2, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("kj,aibk->bjai", extract_mat(F, "oo", o, v), extract_mat(c2, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("ac,cibj->bjai", extract_mat(F, "vv", o, v), extract_mat(c2, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("bc,cjai->bjai", extract_mat(F, "vv", o, v), extract_mat(c2, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("ci,acbj->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "vvvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("cj,aibc->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "vovv", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("ak,kibj->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "oovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("bk,kjai->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "oovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +4.00000000  * fixed_einsum("ckai,kcbj->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("ckai,kjbc->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "oovv", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +4.00000000  * fixed_einsum("ckbj,kcai->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("ckbj,kiac->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "oovv", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("cidj,acbd->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "vvvv", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("ciak,kcbj->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("cibk,kjac->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "oovv", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("cjak,kibc->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "oovv", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("cjbk,kcai->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("akbl,kilj->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "oooo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("kc,ci,akbj->bjai", extract_mat(F, "ov", o, v), extract_mat(c1, "vo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("kc,cj,aibk->bjai", extract_mat(F, "ov", o, v), extract_mat(c1, "vo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("kc,ak,cibj->bjai", extract_mat(F, "ov", o, v), extract_mat(c1, "vo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("kc,bk,cjai->bjai", extract_mat(F, "ov", o, v), extract_mat(c1, "vo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("ck,kcli,albj->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovoo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("ck,kclj,aibl->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovoo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("ck,kcad,dibj->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovvv", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("ck,kcbd,djai->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovvv", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("ck,kdac,dibj->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovvv", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("ck,kdbc,djai->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovvv", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("ck,kilc,albj->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ooov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("ck,kjlc,aibl->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ooov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("ci,kclj,akbl->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovoo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("ci,kcad,dkbj->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovvv", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("ci,kcbd,djak->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovvv", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("ci,kdac,dkbj->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovvv", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("ci,kdac,djbk->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovvv", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("cj,kcli,albk->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovoo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("cj,kcad,dibk->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovvv", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("cj,kcbd,dkai->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovvv", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("cj,kdbc,dkai->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovvv", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("cj,kdbc,diak->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovvv", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("ak,kcli,clbj->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovoo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("ak,kclj,cibl->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovoo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("ak,kcbd,cidj->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovvv", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("ak,kilc,clbj->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ooov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("ak,kilc,cjbl->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ooov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("bk,kcli,cjal->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovoo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("bk,kclj,clai->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovoo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("bk,kcad,cjdi->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovvv", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("bk,kjlc,clai->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ooov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("bk,kjlc,cial->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ooov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -4.00000000  * fixed_einsum("ckdi,kcld,albj->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("ckdi,kdlc,albj->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -4.00000000  * fixed_einsum("ckdj,kcld,aibl->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("ckdj,kdlc,aibl->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -4.00000000  * fixed_einsum("ckal,kcld,dibj->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("ckal,kdlc,dibj->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +8.00000000  * fixed_einsum("ckai,kcld,dlbj->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -4.00000000  * fixed_einsum("ckai,kcld,djbl->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -4.00000000  * fixed_einsum("ckai,kdlc,dlbj->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("ckai,kdlc,djbl->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -4.00000000  * fixed_einsum("ckbl,kcld,djai->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("ckbl,kdlc,djai->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +8.00000000  * fixed_einsum("ckbj,kcld,dlai->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -4.00000000  * fixed_einsum("ckbj,kcld,dial->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -4.00000000  * fixed_einsum("ckbj,kdlc,dlai->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("ckbj,kdlc,dial->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("cidj,kcld,akbl->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -4.00000000  * fixed_einsum("ciak,kcld,dlbj->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("ciak,kcld,djbl->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("ciak,kdlc,dlbj->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("cibk,kdlc,djal->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("cibj,kcld,dkal->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -4.00000000  * fixed_einsum("cibj,kcld,dlak->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("cjak,kdlc,dibl->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("cjai,kcld,dkbl->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -4.00000000  * fixed_einsum("cjai,kcld,dlbk->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -4.00000000  * fixed_einsum("cjbk,kcld,dlai->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("cjbk,kcld,dial->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("cjbk,kdlc,dlai->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("akbl,kcld,cidj->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("akbj,kcld,cldi->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -4.00000000  * fixed_einsum("akbj,kcld,cidl->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("aibk,kcld,cldj->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -4.00000000  * fixed_einsum("aibk,kcld,cjdl->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
