E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("ci,acbj->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "vvvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("cj,aibc->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "vovv", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("ak,kibj->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "oovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("bk,kjai->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "oovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("kc,ci,akbj->bjai", extract_mat(F, "ov", o, v), extract_mat(c1, "vo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("kc,cj,aibk->bjai", extract_mat(F, "ov", o, v), extract_mat(c1, "vo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("kc,ak,cibj->bjai", extract_mat(F, "ov", o, v), extract_mat(c1, "vo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("kc,bk,cjai->bjai", extract_mat(F, "ov", o, v), extract_mat(c1, "vo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("ci,Aac,Abj->bjai", extract_mat(c1, "vo", o, v), extract_mat(g_p, "IVvv", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("cj,Abc,Aai->bjai", extract_mat(c1, "vo", o, v), extract_mat(g_p, "IVvv", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("ak,Aki,Abj->bjai", extract_mat(c1, "vo", o, v), extract_mat(g_p, "IVoo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("bk,Akj,Aai->bjai", extract_mat(c1, "vo", o, v), extract_mat(g_p, "IVoo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("ci,kc,akbj->bjai", extract_mat(c1, "vo", o, v), extract_mat(g_p, "IIov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("cj,kc,aibk->bjai", extract_mat(c1, "vo", o, v), extract_mat(g_p, "IIov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("ak,kc,cibj->bjai", extract_mat(c1, "vo", o, v), extract_mat(g_p, "IIov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("bk,kc,cjai->bjai", extract_mat(c1, "vo", o, v), extract_mat(g_p, "IIov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("kcli,ck,albj->bjai", extract_mat(L, "ovoo", o, v), extract_mat(c1, "vo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("kclj,ck,aibl->bjai", extract_mat(L, "ovoo", o, v), extract_mat(c1, "vo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("kcad,ck,dibj->bjai", extract_mat(L, "ovvv", o, v), extract_mat(c1, "vo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("kcbd,ck,djai->bjai", extract_mat(L, "ovvv", o, v), extract_mat(c1, "vo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("ci,kclj,akbl->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovoo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("ci,kcad,dkbj->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovvv", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("ci,kcbd,djak->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovvv", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("cj,kcli,albk->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovoo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("cj,kcad,dibk->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovvv", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("cj,kcbd,dkai->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovvv", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("ak,kcli,clbj->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovoo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("ak,kclj,cibl->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovoo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("ak,kcbd,cidj->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovvv", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("bk,kcli,cjal->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovoo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("bk,kclj,clai->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovoo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("bk,kcad,cjdi->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovvv", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("ci,kdac,dkbj->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovvv", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("cj,kdbc,dkai->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovvv", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("ak,kilc,clbj->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ooov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("bk,kjlc,clai->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ooov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("ck,Akc,Aaibj->bjai", extract_mat(c1, "vo", o, v), extract_mat(g_p, "IVov", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("ci,Akc,Aakbj->bjai", extract_mat(c1, "vo", o, v), extract_mat(g_p, "IVov", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("cj,Akc,Aaibk->bjai", extract_mat(c1, "vo", o, v), extract_mat(g_p, "IVov", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("ak,Akc,Acibj->bjai", extract_mat(c1, "vo", o, v), extract_mat(g_p, "IVov", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("bk,Akc,Acjai->bjai", extract_mat(c1, "vo", o, v), extract_mat(g_p, "IVov", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
