E_ai[:,:] = E_ai[:,:] .+  -0.50000000  * fixed_einsum("ii->ai", extract_mat(F, "oo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.50000000  * fixed_einsum("aa->ai", extract_mat(F, "vv", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.50000000  * fixed_einsum("iaai->ai", extract_mat(L, "ovvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +1.00000000  * fixed_einsum("jj->ai", extract_mat(F, "oo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.50000000  * fixed_einsum("ja,aj->ai", extract_mat(F, "ov", o, v), extract_mat(t, "vo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.50000000  * fixed_einsum("ib,bi->ai", extract_mat(F, "ov", o, v), extract_mat(t, "vo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.50000000  * fixed_einsum("jiia,aj->ai", extract_mat(L, "ooov", o, v), extract_mat(t, "vo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.50000000  * fixed_einsum("iaab,bi->ai", extract_mat(L, "ovvv", o, v), extract_mat(t, "vo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.50000000  * fixed_einsum("jjkk->ai", extract_mat(L, "oooo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +1.00000000  * fixed_einsum("jb,bj->ai", extract_mat(F, "ov", o, v), extract_mat(t, "vo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.50000000  * fixed_einsum("jbii,bj->ai", extract_mat(L, "ovoo", o, v), extract_mat(t, "vo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.50000000  * fixed_einsum("jbaa,bj->ai", extract_mat(L, "ovvv", o, v), extract_mat(t, "vo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.50000000  * fixed_einsum("jbia,aibj->ai", extract_mat(L, "ovov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.50000000  * fixed_einsum("jbia,aj,bi->ai", extract_mat(L, "ovov", o, v), extract_mat(t, "vo", o, v), extract_mat(t, "vo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.50000000  * fixed_einsum("jakb,ajbk->ai", extract_mat(g, "ovov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.50000000  * fixed_einsum("jbic,bjci->ai", extract_mat(g, "ovov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.50000000  * fixed_einsum("jakb,aj,bk->ai", extract_mat(L, "ovov", o, v), extract_mat(t, "vo", o, v), extract_mat(t, "vo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.50000000  * fixed_einsum("jbic,bj,ci->ai", extract_mat(L, "ovov", o, v), extract_mat(t, "vo", o, v), extract_mat(t, "vo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.50000000  * fixed_einsum("jbkc,bjck->ai", extract_mat(g, "ovov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.50000000  * fixed_einsum("jbkc,bj,ck->ai", extract_mat(L, "ovov", o, v), extract_mat(t, "vo", o, v), extract_mat(t, "vo", o, v), optimize="optimal");
