E_ai[:,:] = E_ai[:,:] .+  -1.00000000  * fixed_einsum("ji,aj->ai", extract_mat(F, "oo", o, v), extract_mat(c1, "vo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +1.00000000  * fixed_einsum("ab,bi->ai", extract_mat(F, "vv", o, v), extract_mat(c1, "vo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +4.00000000  * fixed_einsum("jb,bjai->ai", extract_mat(F, "ov", o, v), extract_mat(c2, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -2.00000000  * fixed_einsum("jb,biaj->ai", extract_mat(F, "ov", o, v), extract_mat(c2, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +1.00000000  * fixed_einsum("jbai,bj->ai", extract_mat(L, "ovvo", o, v), extract_mat(c1, "vo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -1.00000000  * fixed_einsum("jb,bi,aj->ai", extract_mat(F, "ov", o, v), extract_mat(c1, "vo", o, v), extract_mat(t, "vo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -1.00000000  * fixed_einsum("jb,aj,bi->ai", extract_mat(F, "ov", o, v), extract_mat(c1, "vo", o, v), extract_mat(t, "vo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -2.00000000  * fixed_einsum("jbki,bjak->ai", extract_mat(L, "ovoo", o, v), extract_mat(c2, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +2.00000000  * fixed_einsum("jbac,bjci->ai", extract_mat(L, "ovvv", o, v), extract_mat(c2, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -1.00000000  * fixed_einsum("jbki,bj,ak->ai", extract_mat(L, "ovoo", o, v), extract_mat(c1, "vo", o, v), extract_mat(t, "vo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -1.00000000  * fixed_einsum("jbki,ak,bj->ai", extract_mat(L, "ovoo", o, v), extract_mat(c1, "vo", o, v), extract_mat(t, "vo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +1.00000000  * fixed_einsum("jbac,bj,ci->ai", extract_mat(L, "ovvv", o, v), extract_mat(c1, "vo", o, v), extract_mat(t, "vo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +1.00000000  * fixed_einsum("jbac,ci,bj->ai", extract_mat(L, "ovvv", o, v), extract_mat(c1, "vo", o, v), extract_mat(t, "vo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +1.00000000  * fixed_einsum("jbkc,bj,aick->ai", extract_mat(L, "ovov", o, v), extract_mat(c1, "vo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -2.00000000  * fixed_einsum("jbkc,bjak,ci->ai", extract_mat(L, "ovov", o, v), extract_mat(c2, "vovo", o, v), extract_mat(t, "vo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +4.00000000  * fixed_einsum("jbkc,bjai,ck->ai", extract_mat(L, "ovov", o, v), extract_mat(c2, "vovo", o, v), extract_mat(t, "vo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -2.00000000  * fixed_einsum("jbkc,bjci,ak->ai", extract_mat(L, "ovov", o, v), extract_mat(c2, "vovo", o, v), extract_mat(t, "vo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -2.00000000  * fixed_einsum("jbkc,biaj,ck->ai", extract_mat(L, "ovov", o, v), extract_mat(c2, "vovo", o, v), extract_mat(t, "vo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -1.00000000  * fixed_einsum("bi,jbkc,ajck->ai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -1.00000000  * fixed_einsum("aj,jbkc,bick->ai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -1.00000000  * fixed_einsum("jbkc,bj,ak,ci->ai", extract_mat(L, "ovov", o, v), extract_mat(c1, "vo", o, v), extract_mat(t, "vo", o, v), extract_mat(t, "vo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -1.00000000  * fixed_einsum("jbkc,bi,aj,ck->ai", extract_mat(L, "ovov", o, v), extract_mat(c1, "vo", o, v), extract_mat(t, "vo", o, v), extract_mat(t, "vo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -1.00000000  * fixed_einsum("jbkc,aj,bi,ck->ai", extract_mat(L, "ovov", o, v), extract_mat(c1, "vo", o, v), extract_mat(t, "vo", o, v), extract_mat(t, "vo", o, v), optimize="optimal");
