E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("ki,akbj->bjai", extract_mat(F, "oo", o, v), extract_mat(c2, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("ki,ajbk->bjai", extract_mat(F, "oo", o, v), extract_mat(c2, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("kj,akbi->bjai", extract_mat(F, "oo", o, v), extract_mat(c2, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("kj,aibk->bjai", extract_mat(F, "oo", o, v), extract_mat(c2, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("ac,cibj->bjai", extract_mat(F, "vv", o, v), extract_mat(c2, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("ac,cjbi->bjai", extract_mat(F, "vv", o, v), extract_mat(c2, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("bc,ciaj->bjai", extract_mat(F, "vv", o, v), extract_mat(c2, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("bc,cjai->bjai", extract_mat(F, "vv", o, v), extract_mat(c2, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.50000000  * fixed_einsum("kibj,ak->bjai", extract_mat(L, "oovo", o, v), extract_mat(c1, "vo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.50000000  * fixed_einsum("kjai,bk->bjai", extract_mat(L, "oovo", o, v), extract_mat(c1, "vo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.50000000  * fixed_einsum("acbj,ci->bjai", extract_mat(L, "vvvo", o, v), extract_mat(c1, "vo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.50000000  * fixed_einsum("aibc,cj->bjai", extract_mat(L, "vovv", o, v), extract_mat(c1, "vo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("kcai,ckbj->bjai", extract_mat(L, "ovvo", o, v), extract_mat(c2, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("kcai,cjbk->bjai", extract_mat(L, "ovvo", o, v), extract_mat(c2, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("kcaj,ckbi->bjai", extract_mat(L, "ovvo", o, v), extract_mat(c2, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("kcbi,ckaj->bjai", extract_mat(L, "ovvo", o, v), extract_mat(c2, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("kcbj,ckai->bjai", extract_mat(L, "ovvo", o, v), extract_mat(c2, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("kcbj,ciak->bjai", extract_mat(L, "ovvo", o, v), extract_mat(c2, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("kilj,akbl->bjai", extract_mat(L, "oooo", o, v), extract_mat(c2, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("kibc,cjak->bjai", extract_mat(L, "oovv", o, v), extract_mat(c2, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("kjac,cibk->bjai", extract_mat(L, "oovv", o, v), extract_mat(c2, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("acbd,cidj->bjai", extract_mat(L, "vvvv", o, v), extract_mat(c2, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.50000000  * fixed_einsum("kc,ci,akbj->bjai", extract_mat(F, "ov", o, v), extract_mat(c1, "vo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.50000000  * fixed_einsum("kc,cj,aibk->bjai", extract_mat(F, "ov", o, v), extract_mat(c1, "vo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.50000000  * fixed_einsum("kc,ak,cibj->bjai", extract_mat(F, "ov", o, v), extract_mat(c1, "vo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.50000000  * fixed_einsum("kc,bk,cjai->bjai", extract_mat(F, "ov", o, v), extract_mat(c1, "vo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.50000000  * fixed_einsum("kcli,ck,albj->bjai", extract_mat(L, "ovoo", o, v), extract_mat(c1, "vo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.50000000  * fixed_einsum("kcli,al,ckbj->bjai", extract_mat(L, "ovoo", o, v), extract_mat(c1, "vo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.50000000  * fixed_einsum("kclj,ck,aibl->bjai", extract_mat(L, "ovoo", o, v), extract_mat(c1, "vo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.50000000  * fixed_einsum("kclj,bl,ckai->bjai", extract_mat(L, "ovoo", o, v), extract_mat(c1, "vo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.50000000  * fixed_einsum("kcad,ck,dibj->bjai", extract_mat(L, "ovvv", o, v), extract_mat(c1, "vo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.50000000  * fixed_einsum("kcad,di,ckbj->bjai", extract_mat(L, "ovvv", o, v), extract_mat(c1, "vo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.50000000  * fixed_einsum("kcbd,ck,djai->bjai", extract_mat(L, "ovvv", o, v), extract_mat(c1, "vo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.50000000  * fixed_einsum("kcbd,dj,ckai->bjai", extract_mat(L, "ovvv", o, v), extract_mat(c1, "vo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.50000000  * fixed_einsum("ci,kclj,akbl->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovoo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.50000000  * fixed_einsum("ci,kcbd,djak->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovvv", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.50000000  * fixed_einsum("ci,kdbc,dkaj->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovvv", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.50000000  * fixed_einsum("cj,kcli,albk->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovoo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.50000000  * fixed_einsum("cj,kcad,dibk->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovvv", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.50000000  * fixed_einsum("cj,kdac,dkbi->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovvv", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.50000000  * fixed_einsum("ak,kclj,cibl->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovoo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.50000000  * fixed_einsum("ak,kcbd,cidj->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovvv", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.50000000  * fixed_einsum("ak,kjlc,clbi->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ooov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.50000000  * fixed_einsum("bk,kcli,cjal->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovoo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.50000000  * fixed_einsum("bk,kcad,cjdi->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ovvv", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.50000000  * fixed_einsum("bk,kilc,claj->bjai", extract_mat(c1, "vo", o, v), extract_mat(g, "ooov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("kcld,ckal,bjdi->bjai", extract_mat(L, "ovov", o, v), extract_mat(c2, "vovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("kcld,ckai,bjdl->bjai", extract_mat(L, "ovov", o, v), extract_mat(c2, "vovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("kcld,ckaj,bidl->bjai", extract_mat(L, "ovov", o, v), extract_mat(c2, "vovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("kcld,ckbl,aidj->bjai", extract_mat(L, "ovov", o, v), extract_mat(c2, "vovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("kcld,ckbi,ajdl->bjai", extract_mat(L, "ovov", o, v), extract_mat(c2, "vovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("kcld,ckbj,aidl->bjai", extract_mat(L, "ovov", o, v), extract_mat(c2, "vovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("kcld,ckdi,albj->bjai", extract_mat(L, "ovov", o, v), extract_mat(c2, "vovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("kcld,ckdj,aibl->bjai", extract_mat(L, "ovov", o, v), extract_mat(c2, "vovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("kcld,ciak,bjdl->bjai", extract_mat(L, "ovov", o, v), extract_mat(c2, "vovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("kcld,cjbk,aidl->bjai", extract_mat(L, "ovov", o, v), extract_mat(c2, "vovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("cidj,kcld,akbl->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("ciaj,kcld,bkdl->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("cibk,kcld,ajdl->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("cibk,kdlc,djal->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("cibj,kcld,akdl->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("cjak,kcld,bidl->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("cjak,kdlc,dibl->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("cjai,kcld,bkdl->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("cjbi,kcld,akdl->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("akbl,kcld,cidj->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("akbi,kcld,cjdl->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("akbj,kcld,cidl->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("aibk,kcld,cjdl->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("ajbk,kcld,cidl->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
