Omega_bjai[:,:,:,:] = Omega_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("aibj->bjai", extract_mat(g, "vovo", o, v), optimize="optimal");
Omega_bjai[:,:,:,:] = Omega_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("ki,akbj->bjai", extract_mat(F, "oo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
Omega_bjai[:,:,:,:] = Omega_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("kj,aibk->bjai", extract_mat(F, "oo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
Omega_bjai[:,:,:,:] = Omega_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("ac,cibj->bjai", extract_mat(F, "vv", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
Omega_bjai[:,:,:,:] = Omega_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("bc,cjai->bjai", extract_mat(F, "vv", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
Omega_bjai[:,:,:,:] = Omega_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("Aai,Abj->bjai", extract_mat(g_p, "IVvo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
Omega_bjai[:,:,:,:] = Omega_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("Abj,Aai->bjai", extract_mat(g_p, "IVvo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
Omega_bjai[:,:,:,:] = Omega_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("ki,akbj->bjai", extract_mat(g_p, "IIoo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
Omega_bjai[:,:,:,:] = Omega_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("kj,aibk->bjai", extract_mat(g_p, "IIoo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
Omega_bjai[:,:,:,:] = Omega_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("ac,cibj->bjai", extract_mat(g_p, "IIvv", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
Omega_bjai[:,:,:,:] = Omega_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("bc,cjai->bjai", extract_mat(g_p, "IIvv", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
Omega_bjai[:,:,:,:] = Omega_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("A,Aaibj->bjai", extract_mat(h_p, "IV", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
Omega_bjai[:,:,:,:] = Omega_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("kiac,bjck->bjai", extract_mat(g, "oovv", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
Omega_bjai[:,:,:,:] = Omega_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("kibc,akcj->bjai", extract_mat(g, "oovv", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
Omega_bjai[:,:,:,:] = Omega_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("kilj,akbl->bjai", extract_mat(g, "oooo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
Omega_bjai[:,:,:,:] = Omega_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("kjac,bkci->bjai", extract_mat(g, "oovv", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
Omega_bjai[:,:,:,:] = Omega_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("kjbc,aick->bjai", extract_mat(g, "oovv", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
Omega_bjai[:,:,:,:] = Omega_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("acbd,cidj->bjai", extract_mat(g, "vvvv", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
Omega_bjai[:,:,:,:] = Omega_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("kcai,bjck->bjai", extract_mat(g, "ovvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
Omega_bjai[:,:,:,:] = Omega_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("kcbj,aick->bjai", extract_mat(g, "ovvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
Omega_bjai[:,:,:,:] = Omega_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("Aac,Abjci->bjai", extract_mat(g_p, "IVvv", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
Omega_bjai[:,:,:,:] = Omega_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("Abc,Aaicj->bjai", extract_mat(g_p, "IVvv", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
Omega_bjai[:,:,:,:] = Omega_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("Aki,Aakbj->bjai", extract_mat(g_p, "IVoo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
Omega_bjai[:,:,:,:] = Omega_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("Akj,Aaibk->bjai", extract_mat(g_p, "IVoo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
Omega_bjai[:,:,:,:] = Omega_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("Akk,Aaibj->bjai", extract_mat(g_p, "IVoo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
Omega_bjai[:,:,:,:] = Omega_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("Akc,Aak,bjci->bjai", extract_mat(g_p, "IVov", o, v), extract_mat(s, "VIvo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
Omega_bjai[:,:,:,:] = Omega_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("Akc,Abk,aicj->bjai", extract_mat(g_p, "IVov", o, v), extract_mat(s, "VIvo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
Omega_bjai[:,:,:,:] = Omega_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("Akc,Aci,akbj->bjai", extract_mat(g_p, "IVov", o, v), extract_mat(s, "VIvo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
Omega_bjai[:,:,:,:] = Omega_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("Akc,Acj,aibk->bjai", extract_mat(g_p, "IVov", o, v), extract_mat(s, "VIvo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
Omega_bjai[:,:,:,:] = Omega_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("Akc,Aai,bjck->bjai", extract_mat(g_p, "IVov", o, v), extract_mat(s, "VIvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
Omega_bjai[:,:,:,:] = Omega_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("Akc,Abj,aick->bjai", extract_mat(g_p, "IVov", o, v), extract_mat(s, "VIvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
Omega_bjai[:,:,:,:] = Omega_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("kcld,akbl,cidj->bjai", extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
Omega_bjai[:,:,:,:] = Omega_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("kcld,akdj,blci->bjai", extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
Omega_bjai[:,:,:,:] = Omega_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("kcld,aicl,bkdj->bjai", extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
Omega_bjai[:,:,:,:] = Omega_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("kcld,akbj,cidl->bjai", extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
Omega_bjai[:,:,:,:] = Omega_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("kcld,aibk,cjdl->bjai", extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
Omega_bjai[:,:,:,:] = Omega_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("kcld,aicj,bkdl->bjai", extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
Omega_bjai[:,:,:,:] = Omega_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("kcld,bjci,akdl->bjai", extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
Omega_bjai[:,:,:,:] = Omega_bjai[:,:,:,:] .+  -1.00000000  * fixed_einsum("kcld,bjcl,aidk->bjai", extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
Omega_bjai[:,:,:,:] = Omega_bjai[:,:,:,:] .+  +1.00000000  * fixed_einsum("kcld,aick,bjdl->bjai", extract_mat(g, "ovov", o, v), extract_mat(u, "vovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
