E_ia[:,:] = E_ia[:,:] .+  +1.00000000  * extract_mat(h_p, "II", o, v) * fixed_einsum("ai->ia", extract_mat(l1, "vo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  +2.00000000  * fixed_einsum("jj,ai->ia", extract_mat(F, "oo", o, v), extract_mat(l1, "vo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  +1.00000000  * fixed_einsum("Aai,A->ia", extract_mat(L2, "VIvo", o, v), extract_mat(h_p, "VI", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  -2.00000000  * fixed_einsum("jj,ai->ia", extract_mat(g_p, "IIoo", o, v), extract_mat(l1, "vo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  +2.00000000  * fixed_einsum("bj,bjai->ia", extract_mat(F, "vo", o, v), extract_mat(l2, "vovo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  -1.00000000  * fixed_einsum("jjkk,ai->ia", extract_mat(L, "oooo", o, v), extract_mat(l1, "vo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  -2.00000000  * fixed_einsum("Aai,Ajj->ia", extract_mat(L2, "VIvo", o, v), extract_mat(g_p, "VIoo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  -2.00000000  * fixed_einsum("bj,bjai->ia", extract_mat(g_p, "IIvo", o, v), extract_mat(l2, "vovo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  -1.00000000  * fixed_einsum("Abjai,Abj->ia", extract_mat(L3, "VIvovo", o, v), extract_mat(g_p, "VIvo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  -1.00000000  * fixed_einsum("Aaibj,Abj->ia", extract_mat(L3, "VIvovo", o, v), extract_mat(g_p, "VIvo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  +2.00000000  * fixed_einsum("jb,Aai,Abj->ia", extract_mat(F, "ov", o, v), extract_mat(L2, "VIvo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  -1.00000000  * extract_mat(h_p, "II", o, v) * fixed_einsum("Abjai,Abj->ia", extract_mat(L3, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  -1.00000000  * extract_mat(h_p, "II", o, v) * fixed_einsum("Aaibj,Abj->ia", extract_mat(L3, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  -2.00000000  * fixed_einsum("Ajb,ai,Abj->ia", extract_mat(g_p, "IVov", o, v), extract_mat(l1, "vo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  +2.00000000  * fixed_einsum("A,bjai,Abj->ia", extract_mat(h_p, "IV", o, v), extract_mat(l2, "vovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  +1.00000000  * fixed_einsum("bc,Abjai,Acj->ia", extract_mat(F, "vv", o, v), extract_mat(L3, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  -1.00000000  * fixed_einsum("jk,Abkai,Abj->ia", extract_mat(F, "oo", o, v), extract_mat(L3, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  +1.00000000  * fixed_einsum("bc,Aaibj,Acj->ia", extract_mat(F, "vv", o, v), extract_mat(L3, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  -1.00000000  * fixed_einsum("jk,Aaibk,Abj->ia", extract_mat(F, "oo", o, v), extract_mat(L3, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  +2.00000000  * fixed_einsum("jb,ckai,bjck->ia", extract_mat(F, "ov", o, v), extract_mat(l2, "vovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  -2.00000000  * fixed_einsum("Aai,ABjb,Bbj->ia", extract_mat(L2, "VIvo", o, v), extract_mat(g_p, "VVov", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  +2.00000000  * fixed_einsum("Abjai,kk,Abj->ia", extract_mat(L3, "VIvovo", o, v), extract_mat(g_p, "IIoo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  +2.00000000  * fixed_einsum("Aaibj,kk,Abj->ia", extract_mat(L3, "VIvovo", o, v), extract_mat(g_p, "IIoo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  +1.00000000  * fixed_einsum("Abjai,AB,Bbj->ia", extract_mat(L3, "VIvovo", o, v), extract_mat(h_p, "VV", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  +1.00000000  * fixed_einsum("Aaibj,AB,Bbj->ia", extract_mat(L3, "VIvovo", o, v), extract_mat(h_p, "VV", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  +1.00000000  * fixed_einsum("jbkc,ai,bjck->ia", extract_mat(g, "ovov", o, v), extract_mat(l1, "vo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  -4.00000000  * fixed_einsum("Ajj,bkai,Abk->ia", extract_mat(g_p, "IVoo", o, v), extract_mat(l2, "vovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  -2.00000000  * fixed_einsum("Abc,bjai,Acj->ia", extract_mat(g_p, "IVvv", o, v), extract_mat(l2, "vovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  +2.00000000  * fixed_einsum("Ajk,bkai,Abj->ia", extract_mat(g_p, "IVoo", o, v), extract_mat(l2, "vovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  -2.00000000  * fixed_einsum("jb,ckai,bjck->ia", extract_mat(g_p, "IIov", o, v), extract_mat(l2, "vovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  +2.00000000  * fixed_einsum("jb,Ackai,Abjck->ia", extract_mat(F, "ov", o, v), extract_mat(L3, "VIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  -1.00000000  * fixed_einsum("jb,Ackai,Abkcj->ia", extract_mat(F, "ov", o, v), extract_mat(L3, "VIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  +2.00000000  * fixed_einsum("jb,Aaick,Abjck->ia", extract_mat(F, "ov", o, v), extract_mat(L3, "VIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  -1.00000000  * fixed_einsum("jb,Aaick,Abkcj->ia", extract_mat(F, "ov", o, v), extract_mat(L3, "VIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  +1.00000000  * fixed_einsum("jbkc,Aai,Abjck->ia", extract_mat(L, "ovov", o, v), extract_mat(L2, "VIvo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  +1.00000000  * fixed_einsum("bjkc,Abjai,Ack->ia", extract_mat(L, "voov", o, v), extract_mat(L3, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  +1.00000000  * fixed_einsum("bjkc,Aaibj,Ack->ia", extract_mat(L, "voov", o, v), extract_mat(L3, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  -1.00000000  * fixed_einsum("Abjai,ABbc,Bcj->ia", extract_mat(L3, "VIvovo", o, v), extract_mat(g_p, "VVvv", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  +1.00000000  * fixed_einsum("Abjai,ABkj,Bbk->ia", extract_mat(L3, "VIvovo", o, v), extract_mat(g_p, "VVoo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  -2.00000000  * fixed_einsum("Abjai,ABkk,Bbj->ia", extract_mat(L3, "VIvovo", o, v), extract_mat(g_p, "VVoo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  -1.00000000  * fixed_einsum("Aaibj,ABbc,Bcj->ia", extract_mat(L3, "VIvovo", o, v), extract_mat(g_p, "VVvv", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  +1.00000000  * fixed_einsum("Aaibj,ABkj,Bbk->ia", extract_mat(L3, "VIvovo", o, v), extract_mat(g_p, "VVoo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  -2.00000000  * fixed_einsum("Aaibj,ABkk,Bbj->ia", extract_mat(L3, "VIvovo", o, v), extract_mat(g_p, "VVoo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  -1.00000000  * fixed_einsum("Abjai,Akc,bjck->ia", extract_mat(L3, "VIvovo", o, v), extract_mat(g_p, "VIov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  -1.00000000  * fixed_einsum("Aaibj,Akc,bjck->ia", extract_mat(L3, "VIvovo", o, v), extract_mat(g_p, "VIov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  +2.00000000  * fixed_einsum("bcjd,bkai,ckdj->ia", extract_mat(g, "vvov", o, v), extract_mat(l2, "vovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  -2.00000000  * fixed_einsum("jklb,ckai,blcj->ia", extract_mat(g, "ooov", o, v), extract_mat(l2, "vovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  -4.00000000  * fixed_einsum("Ajb,ckai,Abjck->ia", extract_mat(g_p, "IVov", o, v), extract_mat(l2, "vovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  +2.00000000  * fixed_einsum("Ajb,ckai,Abkcj->ia", extract_mat(g_p, "IVov", o, v), extract_mat(l2, "vovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  -1.00000000  * fixed_einsum("jklb,Ackai,Acjbl->ia", extract_mat(L, "ooov", o, v), extract_mat(L3, "VIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  -1.00000000  * fixed_einsum("jklb,Aaick,Acjbl->ia", extract_mat(L, "ooov", o, v), extract_mat(L3, "VIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  +2.00000000  * fixed_einsum("Abjai,bckd,Acjdk->ia", extract_mat(L3, "VIvovo", o, v), extract_mat(g, "vvov", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  -1.00000000  * fixed_einsum("Abjai,bckd,Ackdj->ia", extract_mat(L3, "VIvovo", o, v), extract_mat(g, "vvov", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  +2.00000000  * fixed_einsum("Aaibj,bckd,Acjdk->ia", extract_mat(L3, "VIvovo", o, v), extract_mat(g, "vvov", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  -1.00000000  * fixed_einsum("Aaibj,bckd,Ackdj->ia", extract_mat(L3, "VIvovo", o, v), extract_mat(g, "vvov", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  -2.00000000  * fixed_einsum("Abjai,ABkc,Bbjck->ia", extract_mat(L3, "VIvovo", o, v), extract_mat(g_p, "VVov", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  +1.00000000  * fixed_einsum("Abjai,ABkc,Bbkcj->ia", extract_mat(L3, "VIvovo", o, v), extract_mat(g_p, "VVov", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  -2.00000000  * fixed_einsum("Aaibj,ABkc,Bbjck->ia", extract_mat(L3, "VIvovo", o, v), extract_mat(g_p, "VVov", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  +1.00000000  * fixed_einsum("Aaibj,ABkc,Bbkcj->ia", extract_mat(L3, "VIvovo", o, v), extract_mat(g_p, "VVov", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  +2.00000000  * fixed_einsum("Abjai,Bkc,Abj,Bck->ia", extract_mat(L3, "VIvovo", o, v), extract_mat(g_p, "IVov", o, v), extract_mat(s, "VIvo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  +2.00000000  * fixed_einsum("Aaibj,Bkc,Abj,Bck->ia", extract_mat(L3, "VIvovo", o, v), extract_mat(g_p, "IVov", o, v), extract_mat(s, "VIvo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  +1.00000000  * fixed_einsum("jbkc,Adlai,Abj,ckdl->ia", extract_mat(L, "ovov", o, v), extract_mat(L3, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  +1.00000000  * fixed_einsum("jbkc,Aaidl,Abj,ckdl->ia", extract_mat(L, "ovov", o, v), extract_mat(L3, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  -1.00000000  * fixed_einsum("Abjai,kcld,Abk,cjdl->ia", extract_mat(L3, "VIvovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(s, "VIvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  -1.00000000  * fixed_einsum("Abjai,kcld,Acj,bkdl->ia", extract_mat(L3, "VIvovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(s, "VIvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  -1.00000000  * fixed_einsum("Aaibj,kcld,Abk,cjdl->ia", extract_mat(L3, "VIvovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(s, "VIvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ia[:,:] = E_ia[:,:] .+  -1.00000000  * fixed_einsum("Aaibj,kcld,Acj,bkdl->ia", extract_mat(L3, "VIvovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(s, "VIvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
