E = E .+  -1.00000000  * fixed_einsum("ai,Baibj,Bbj->", extract_mat(g_p, "IIvo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E = E .+  +0.50000000  * fixed_einsum("ai,Bajbi,Bbj->", extract_mat(g_p, "IIvo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E = E .+  +0.50000000  * fixed_einsum("ai,Bbiaj,Bbj->", extract_mat(g_p, "IIvo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E = E .+  -1.00000000  * fixed_einsum("ai,Bbjai,Bbj->", extract_mat(g_p, "IIvo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E = E .+  +1.00000000  * fixed_einsum("Bai,aibj,Bbj->", extract_mat(g_p, "IVvo", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E = E .+  -0.50000000  * fixed_einsum("Bai,ajbi,Bbj->", extract_mat(g_p, "IVvo", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E = E .+  -0.50000000  * fixed_einsum("Bai,biaj,Bbj->", extract_mat(g_p, "IVvo", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E = E .+  +1.00000000  * fixed_einsum("Bai,bjai,Bbj->", extract_mat(g_p, "IVvo", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E = E .+  +0.50000000  * fixed_einsum("ab,aicj,bicj->", extract_mat(g_p, "IIvv", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E = E .+  -0.50000000  * fixed_einsum("ij,ajbk,aibk->", extract_mat(g_p, "IIoo", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E = E .+  +0.50000000  * fixed_einsum("ab,ciaj,bjci->", extract_mat(g_p, "IIvv", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E = E .+  -0.50000000  * fixed_einsum("ij,akbj,akbi->", extract_mat(g_p, "IIoo", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E = E .+  +1.00000000  * extract_mat(h_p, "II", o, v) * fixed_einsum("Baibj,Baibj->", extract_mat(p2, "VIvovo", o, v), extract_mat(s2, "VAvovo", o, v), optimize="optimal");
E = E .+  -0.50000000  * extract_mat(h_p, "II", o, v) * fixed_einsum("Baibj,Bajbi->", extract_mat(p2, "VIvovo", o, v), extract_mat(s2, "VAvovo", o, v), optimize="optimal");
E = E .+  -1.00000000  * fixed_einsum("B,aibj,Baibj->", extract_mat(h_p, "IV", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E = E .+  +0.50000000  * fixed_einsum("B,aibj,Bajbi->", extract_mat(h_p, "IV", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E = E .+  -2.00000000  * fixed_einsum("ii,Bajbk,Bajbk->", extract_mat(g_p, "IIoo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s2, "VAvovo", o, v), optimize="optimal");
E = E .+  +1.00000000  * fixed_einsum("ii,Bajbk,Bakbj->", extract_mat(g_p, "IIoo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s2, "VAvovo", o, v), optimize="optimal");
E = E .+  +2.00000000  * fixed_einsum("Bii,ajbk,Bajbk->", extract_mat(g_p, "IVoo", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E = E .+  -1.00000000  * fixed_einsum("Bii,ajbk,Bakbj->", extract_mat(g_p, "IVoo", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E = E .+  +1.00000000  * fixed_einsum("Bab,aicj,Bbicj->", extract_mat(g_p, "IVvv", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E = E .+  -0.50000000  * fixed_einsum("Bab,aicj,Bbjci->", extract_mat(g_p, "IVvv", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E = E .+  -1.00000000  * fixed_einsum("Bij,ajbk,Baibk->", extract_mat(g_p, "IVoo", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E = E .+  +0.50000000  * fixed_einsum("Bij,ajbk,Bakbi->", extract_mat(g_p, "IVoo", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E = E .+  -0.50000000  * fixed_einsum("Bab,ciaj,Bbicj->", extract_mat(g_p, "IVvv", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E = E .+  +1.00000000  * fixed_einsum("Bab,ciaj,Bbjci->", extract_mat(g_p, "IVvv", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E = E .+  +0.50000000  * fixed_einsum("Bij,akbj,Baibk->", extract_mat(g_p, "IVoo", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E = E .+  -1.00000000  * fixed_einsum("Bij,akbj,Bakbi->", extract_mat(g_p, "IVoo", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E = E .+  -0.50000000  * fixed_einsum("Bab,Baicj,bicj->", extract_mat(g_p, "VAvv", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E = E .+  +0.50000000  * fixed_einsum("Bij,Bajbk,aibk->", extract_mat(g_p, "VAoo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E = E .+  -0.50000000  * fixed_einsum("Bab,Bciaj,bjci->", extract_mat(g_p, "VAvv", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E = E .+  +0.50000000  * fixed_einsum("Bij,Bakbj,akbi->", extract_mat(g_p, "VAoo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E = E .+  +1.00000000  * fixed_einsum("B,Caibj,Bai,Cbj->", extract_mat(h_p, "IV", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E = E .+  -0.50000000  * fixed_einsum("B,Caibj,Baj,Cbi->", extract_mat(h_p, "IV", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E = E .+  -0.50000000  * fixed_einsum("B,Caibj,Bbi,Caj->", extract_mat(h_p, "IV", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E = E .+  +1.00000000  * fixed_einsum("B,Caibj,Bbj,Cai->", extract_mat(h_p, "IV", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E = E .+  -2.00000000  * fixed_einsum("Bii,Cajbk,Baj,Cbk->", extract_mat(g_p, "IVoo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E = E .+  +1.00000000  * fixed_einsum("Bii,Cajbk,Bak,Cbj->", extract_mat(g_p, "IVoo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E = E .+  +1.00000000  * fixed_einsum("Bii,Cajbk,Bbj,Cak->", extract_mat(g_p, "IVoo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E = E .+  -2.00000000  * fixed_einsum("Bii,Cajbk,Bbk,Caj->", extract_mat(g_p, "IVoo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E = E .+  -1.00000000  * fixed_einsum("Bab,Caicj,Bbi,Ccj->", extract_mat(g_p, "IVvv", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E = E .+  +0.50000000  * fixed_einsum("Bab,Caicj,Bbj,Cci->", extract_mat(g_p, "IVvv", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E = E .+  +1.00000000  * fixed_einsum("Bij,Cajbk,Bai,Cbk->", extract_mat(g_p, "IVoo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E = E .+  -0.50000000  * fixed_einsum("Bij,Cajbk,Bbi,Cak->", extract_mat(g_p, "IVoo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E = E .+  +0.50000000  * fixed_einsum("Bab,Cciaj,Bbi,Ccj->", extract_mat(g_p, "IVvv", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E = E .+  -1.00000000  * fixed_einsum("Bab,Cciaj,Bbj,Cci->", extract_mat(g_p, "IVvv", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E = E .+  -0.50000000  * fixed_einsum("Bij,Cakbj,Bai,Cbk->", extract_mat(g_p, "IVoo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E = E .+  +1.00000000  * fixed_einsum("Bij,Cakbj,Bbi,Cak->", extract_mat(g_p, "IVoo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E = E .+  -1.00000000  * fixed_einsum("ia,Bbjck,Bbj,aick->", extract_mat(g_p, "IIov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E = E .+  +0.50000000  * fixed_einsum("ia,Bbjck,Bbk,aicj->", extract_mat(g_p, "IIov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E = E .+  +0.50000000  * fixed_einsum("ia,Bbjck,Bcj,aibk->", extract_mat(g_p, "IIov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E = E .+  -1.00000000  * fixed_einsum("ia,Bbjck,Bck,aibj->", extract_mat(g_p, "IIov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E = E .+  -0.50000000  * fixed_einsum("Bia,bjck,Baj,bick->", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E = E .+  -0.50000000  * fixed_einsum("Bia,bjck,Bak,bjci->", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E = E .+  -0.50000000  * fixed_einsum("Bia,bjck,Bbi,ajck->", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E = E .+  +1.00000000  * fixed_einsum("Bia,bjck,Bbj,aick->", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E = E .+  -0.50000000  * fixed_einsum("Bia,bjck,Bbk,aicj->", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E = E .+  -0.50000000  * fixed_einsum("Bia,bjck,Bci,akbj->", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E = E .+  -0.50000000  * fixed_einsum("Bia,bjck,Bcj,aibk->", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E = E .+  +1.00000000  * fixed_einsum("Bia,bjck,Bck,aibj->", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E = E .+  -2.00000000  * fixed_einsum("Bia,Cbjck,Bai,Cbjck->", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(s2, "VAvovo", o, v), optimize="optimal");
E = E .+  +1.00000000  * fixed_einsum("Bia,Cbjck,Bai,Cbkcj->", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(s2, "VAvovo", o, v), optimize="optimal");
E = E .+  -2.00000000  * fixed_einsum("Bia,Cbjck,Cbj,Baick->", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E = E .+  +1.00000000  * fixed_einsum("Bia,Cbjck,Cbj,Bakci->", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E = E .+  +1.00000000  * fixed_einsum("Bia,Cbjck,Cbk,Baicj->", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E = E .+  -0.50000000  * fixed_einsum("Bia,Cbjck,Cbk,Bajci->", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E = E .+  +1.00000000  * fixed_einsum("Bia,Cbjck,Ccj,Baibk->", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E = E .+  -0.50000000  * fixed_einsum("Bia,Cbjck,Ccj,Bakbi->", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E = E .+  -2.00000000  * fixed_einsum("Bia,Cbjck,Cck,Baibj->", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E = E .+  +1.00000000  * fixed_einsum("Bia,Cbjck,Cck,Bajbi->", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
