E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("ca,cibj->bjai", extract_mat(F, "vv", o, v), extract_mat(c2, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("cb,cjai->bjai", extract_mat(F, "vv", o, v), extract_mat(c2, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("ik,akbj->bjai", extract_mat(F, "oo", o, v), extract_mat(c2, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("jk,aibk->bjai", extract_mat(F, "oo", o, v), extract_mat(c2, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("cibj,ca->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g_p, "IIvv", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("cjai,cb->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g_p, "IIvv", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("akbj,ik->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g_p, "IIoo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("aibk,jk->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g_p, "IIoo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("ckia,ckbj->bjai", extract_mat(L, "voov", o, v), extract_mat(c2, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("ckjb,ckai->bjai", extract_mat(L, "voov", o, v), extract_mat(c2, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("cidj,cadb->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "vvvv", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("ciak,ckjb->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "voov", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("cibk,cajk->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "vvoo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("cjak,cbik->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "vvoo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("cjbk,ckia->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "voov", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("akbl,ikjl->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "oooo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -4.00000000  * fixed_einsum("ckai,Ajb,Ack->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g_p, "IVov", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -4.00000000  * fixed_einsum("ckbj,Aia,Ack->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g_p, "IVov", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("ciak,Ajb,Ack->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g_p, "IVov", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("cibj,Aka,Ack->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g_p, "IVov", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("cjai,Akb,Ack->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g_p, "IVov", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("cjbk,Aia,Ack->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g_p, "IVov", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("akbj,Aic,Ack->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g_p, "IVov", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("aibk,Ajc,Ack->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g_p, "IVov", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("kcia,dlbj,ckdl->bjai", extract_mat(L, "ovov", o, v), extract_mat(c2, "vovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("kcjb,dlai,ckdl->bjai", extract_mat(L, "ovov", o, v), extract_mat(c2, "vovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("cidj,kalb,ckdl->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("ciak,lbjd,ckdl->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("cibk,lajd,cldk->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("cjak,lbid,cldk->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("cjbk,laid,ckdl->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +2.00000000  * fixed_einsum("akbl,icjd,ckdl->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("ckdi,lajb,ckdl->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("ckdj,lbia,ckdl->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("ckal,idjb,ckdl->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("ckbl,iajd,ckdl->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("ciak,ldjb,ckdl->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("cibj,kdla,cldk->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("cjai,kdlb,cldk->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("cjbk,ldia,ckdl->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("akbj,lcid,cldk->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -2.00000000  * fixed_einsum("aibk,lcjd,cldk->bjai", extract_mat(c2, "vovo", o, v), extract_mat(g, "ovov", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
