E_ai[:,:] = E_ai[:,:] .+  +0.50000000  * fixed_einsum("bj,bjai->ai", extract_mat(g_p, "IIvo", o, v), extract_mat(p2, "AIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("bj,biaj->ai", extract_mat(g_p, "IIvo", o, v), extract_mat(p2, "AIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("bj,ajbi->ai", extract_mat(g_p, "IIvo", o, v), extract_mat(p2, "AIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.50000000  * fixed_einsum("bj,aibj->ai", extract_mat(g_p, "IIvo", o, v), extract_mat(p2, "AIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("bjca,bjci->ai", extract_mat(L, "vovv", o, v), extract_mat(p2, "AIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("bjca,cibj->ai", extract_mat(L, "vovv", o, v), extract_mat(p2, "AIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("bjik,bjak->ai", extract_mat(L, "vooo", o, v), extract_mat(p2, "AIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("bjik,akbj->ai", extract_mat(L, "vooo", o, v), extract_mat(p2, "AIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.50000000  * fixed_einsum("Bbj,Bbjai->ai", extract_mat(g_p, "VAvo", o, v), extract_mat(p2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("Bbj,Bbiaj->ai", extract_mat(g_p, "VAvo", o, v), extract_mat(p2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("Bbj,Bajbi->ai", extract_mat(g_p, "VAvo", o, v), extract_mat(p2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.50000000  * fixed_einsum("Bbj,Baibj->ai", extract_mat(g_p, "VAvo", o, v), extract_mat(p2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.50000000  * extract_mat(h_p, "II", o, v) * fixed_einsum("Bbjai,Bbj->ai", extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * extract_mat(h_p, "II", o, v) * fixed_einsum("Bbiaj,Bbj->ai", extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * extract_mat(h_p, "II", o, v) * fixed_einsum("Bajbi,Bbj->ai", extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.50000000  * extract_mat(h_p, "II", o, v) * fixed_einsum("Baibj,Bbj->ai", extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.50000000  * fixed_einsum("B,bjai,Bbj->ai", extract_mat(h_p, "IV", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("B,biaj,Bbj->ai", extract_mat(h_p, "IV", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("B,ajbi,Bbj->ai", extract_mat(h_p, "IV", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.50000000  * fixed_einsum("B,aibj,Bbj->ai", extract_mat(h_p, "IV", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("ba,Bbjci,Bcj->ai", extract_mat(F, "vv", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.50000000  * fixed_einsum("ba,Bbicj,Bcj->ai", extract_mat(F, "vv", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.50000000  * fixed_einsum("ba,Bcjbi,Bcj->ai", extract_mat(F, "vv", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("ba,Bcibj,Bcj->ai", extract_mat(F, "vv", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("ij,Bbjak,Bbk->ai", extract_mat(F, "oo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.50000000  * fixed_einsum("ij,Bbkaj,Bbk->ai", extract_mat(F, "oo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.50000000  * fixed_einsum("ij,Bajbk,Bbk->ai", extract_mat(F, "oo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("ij,Bakbj,Bbk->ai", extract_mat(F, "oo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("ja,bkci,bkcj->ai", extract_mat(F, "ov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("ja,bick,bjck->ai", extract_mat(F, "ov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("ib,cjak,bkcj->ai", extract_mat(F, "ov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("ib,ajck,bjck->ai", extract_mat(F, "ov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -1.00000000  * fixed_einsum("jj,Bbkai,Bbk->ai", extract_mat(g_p, "IIoo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.50000000  * fixed_einsum("jj,Bbiak,Bbk->ai", extract_mat(g_p, "IIoo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.50000000  * fixed_einsum("jj,Bakbi,Bbk->ai", extract_mat(g_p, "IIoo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -1.00000000  * fixed_einsum("jj,Baibk,Bbk->ai", extract_mat(g_p, "IIoo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +1.00000000  * fixed_einsum("Bjj,bkai,Bbk->ai", extract_mat(g_p, "IVoo", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.50000000  * fixed_einsum("Bjj,biak,Bbk->ai", extract_mat(g_p, "IVoo", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.50000000  * fixed_einsum("Bjj,akbi,Bbk->ai", extract_mat(g_p, "IVoo", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +1.00000000  * fixed_einsum("Bjj,aibk,Bbk->ai", extract_mat(g_p, "IVoo", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.50000000  * fixed_einsum("Bbc,bjai,Bcj->ai", extract_mat(g_p, "IVvv", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("Bbc,biaj,Bcj->ai", extract_mat(g_p, "IVvv", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.50000000  * fixed_einsum("Bjk,bkai,Bbj->ai", extract_mat(g_p, "IVoo", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("Bjk,biak,Bbj->ai", extract_mat(g_p, "IVoo", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("Bjk,akbi,Bbj->ai", extract_mat(g_p, "IVoo", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("Bbc,ajbi,Bcj->ai", extract_mat(g_p, "IVvv", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.50000000  * fixed_einsum("Bbc,aibj,Bcj->ai", extract_mat(g_p, "IVvv", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.50000000  * fixed_einsum("Bjk,aibk,Bbj->ai", extract_mat(g_p, "IVoo", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.50000000  * fixed_einsum("jb,ckai,bjck->ai", extract_mat(g_p, "IIov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("jb,ciak,bjck->ai", extract_mat(g_p, "IIov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("jb,akci,bjck->ai", extract_mat(g_p, "IIov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.50000000  * fixed_einsum("jb,aick,bjck->ai", extract_mat(g_p, "IIov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -1.00000000  * fixed_einsum("ia,Bbjck,Bbjck->ai", extract_mat(F, "ov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s2, "VAvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.50000000  * fixed_einsum("ia,Bbjck,Bbkcj->ai", extract_mat(F, "ov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s2, "VAvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.50000000  * fixed_einsum("bjia,Bbjck,Bck->ai", extract_mat(L, "voov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("bjia,Bbkcj,Bck->ai", extract_mat(L, "voov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("bjia,Bcjbk,Bck->ai", extract_mat(L, "voov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.50000000  * fixed_einsum("bjia,Bckbj,Bck->ai", extract_mat(L, "voov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jbca,cidk,bjdk->ai", extract_mat(L, "ovvv", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jbca,dkci,bjdk->ai", extract_mat(L, "ovvv", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("jbik,clak,bjcl->ai", extract_mat(L, "ovoo", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("jbik,akcl,bjcl->ai", extract_mat(L, "ovoo", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("bcia,bjdk,cjdk->ai", extract_mat(L, "vvov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("jkia,bkcl,bjcl->ai", extract_mat(L, "ooov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("bcia,djbk,ckdj->ai", extract_mat(L, "vvov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("jkia,blck,blcj->ai", extract_mat(L, "ooov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("bcja,bkdi,ckdj->ai", extract_mat(g, "vvov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("jbca,ckdi,bjdk->ai", extract_mat(g, "ovvv", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jkla,bkci,bjcl->ai", extract_mat(g, "ooov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("bcja,dibk,ckdj->ai", extract_mat(g, "vvov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("jbca,dick,bjdk->ai", extract_mat(g, "ovvv", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jkla,bick,blcj->ai", extract_mat(g, "ooov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("bcid,bjak,cjdk->ai", extract_mat(g, "vvov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jkib,ckal,blcj->ai", extract_mat(g, "ooov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jbik,ckal,bjcl->ai", extract_mat(g, "ovoo", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("bcid,ajbk,ckdj->ai", extract_mat(g, "vvov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jkib,alck,blcj->ai", extract_mat(g, "ooov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jbik,alck,bjcl->ai", extract_mat(g, "ovoo", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +1.00000000  * fixed_einsum("Bjb,ckai,Bbjck->ai", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.50000000  * fixed_einsum("Bjb,ckai,Bbkcj->ai", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.50000000  * fixed_einsum("Bjb,ciak,Bbjck->ai", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("Bjb,ciak,Bbkcj->ai", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.50000000  * fixed_einsum("Bjb,akci,Bbjck->ai", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("Bjb,akci,Bbkcj->ai", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +1.00000000  * fixed_einsum("Bjb,aick,Bbjck->ai", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.50000000  * fixed_einsum("Bjb,aick,Bbkcj->ai", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.50000000  * fixed_einsum("Bjb,Bckai,bjck->ai", extract_mat(g_p, "VAov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("Bjb,Bciak,bjck->ai", extract_mat(g_p, "VAov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("Bjb,Bakci,bjck->ai", extract_mat(g_p, "VAov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.50000000  * fixed_einsum("Bjb,Baick,bjck->ai", extract_mat(g_p, "VAov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("Bja,Bbkci,bkcj->ai", extract_mat(g_p, "VAov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("Bja,Bbick,bjck->ai", extract_mat(g_p, "VAov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("Bib,Bcjak,bkcj->ai", extract_mat(g_p, "VAov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("Bib,Bajck,bjck->ai", extract_mat(g_p, "VAov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -1.00000000  * fixed_einsum("Bjb,Cckai,Bbj,Cck->ai", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.50000000  * fixed_einsum("Bjb,Cciak,Bbj,Cck->ai", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.50000000  * fixed_einsum("Bjb,Cakci,Bbj,Cck->ai", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -1.00000000  * fixed_einsum("Bjb,Caick,Bbj,Cck->ai", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(s, "VAvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.50000000  * fixed_einsum("jbia,Bckdl,Bck,bjdl->ai", extract_mat(L, "ovov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jbia,Bckdl,Bcl,bjdk->ai", extract_mat(L, "ovov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jbia,Bckdl,Bdk,bjcl->ai", extract_mat(L, "ovov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.50000000  * fixed_einsum("jbia,Bckdl,Bdl,bjck->ai", extract_mat(L, "ovov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.50000000  * fixed_einsum("jbka,Bcldi,Bcl,bjdk->ai", extract_mat(g, "ovov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("jbka,Bcldi,Bdl,bjck->ai", extract_mat(g, "ovov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("jbka,Bcidl,Bcl,bjdk->ai", extract_mat(g, "ovov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.50000000  * fixed_einsum("jbka,Bcidl,Bdl,bjck->ai", extract_mat(g, "ovov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.50000000  * fixed_einsum("jbic,Bdkal,Bdk,bjcl->ai", extract_mat(g, "ovov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("jbic,Bdkal,Bdl,bjck->ai", extract_mat(g, "ovov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("jbic,Bakdl,Bdk,bjcl->ai", extract_mat(g, "ovov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.50000000  * fixed_einsum("jbic,Bakdl,Bdl,bjck->ai", extract_mat(g, "ovov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VAvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");